.SILENT:

AR_sparc=/usr/local/bin/sparc-elf-ar rcs
AR_x86=/usr/bin/ar rcs
AWK=/usr/bin/gawk
CAT=/bin/cat
CC_sparc=/usr/local/bin/sparc-elf-gcc
CC_x86=/usr/bin/gcc
CD=cd
CONFIG_CFLAGS=-W -Wall -g -m32
CONFIG_LDFLAGS=--warn-common
CONFIG_QEMU_x86= -fda $(POK_PATH)/misc/grub-boot-only.img 
COPY=/bin/cp
CP=/bin/cp
CXX_x86=/usr/bin/g++
ECHO=/bin/echo
ELF_MODE=elf_i386
GREP=/bin/grep
GZIP=/usr/bin/gzip
INSTRUMENTATION=0
KILL=/usr/bin/kill
LD_sparc=/usr/local/bin/sparc-elf-ld
LD_x86=/usr/bin/ld
MKDIR=/bin/mkdir
MV=/bin/mv
OBJCOPY_sparc=/usr/local/bin/sparc-elf-objcopy
OBJCOPY_x86=/usr/bin/objcopy
OBJDUMP_sparc=/usr/local/bin/sparc-elf-objdump
OBJDUMP_x86=/usr/bin/objdump
PERL=/usr/bin/perl
QEMU_ppc=/usr/local/bin/qemu-system-ppc
QEMU_sparc=/usr/local/bin/qemu-system-sparc
QEMU_x86=/usr/local/bin/qemu
RANLIB_sparc=/usr/local/bin/sparc-elf-ranlib
RANLIB_x86=/usr/bin/ranlib
RM=/bin/rm -r -f
SED=/bin/sed
SLEEP=/bin/sleep
TOUCH=/bin/touch
TSIM_sparc=/usr/bin/tsim-leon3
