/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_hello_part1 ();

/************************/
/* test__hello_part1   */ 
/***********************/

void test__hello_part1 ()
{

  user_hello_part1 ();
}


