/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void bsp_start ();

/************************/
/* test__hello_part2   */ 
/***********************/

void test__hello_part2 ()
{

  bsp_start ();
}


